/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as harVotingSol from "./HarVoting.sol";
export type { harVotingSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Harpolis } from "./Harpolis";
export type { TaxToken } from "./TaxToken";
export * as factories from "./factories";
export { Harpolis__factory } from "./factories/Harpolis__factory";
export type { QVVoting } from "./HarVoting.sol/QVVoting";
export { QVVoting__factory } from "./factories/HarVoting.sol/QVVoting__factory";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
export { TaxToken__factory } from "./factories/TaxToken__factory";
